### PR TITLE
Add ICM20948 driver

### LINKED ISSUE #33: ICM20948 Driver (IMU on FCBv1)
In GitLab by @bf2799 on Nov 8, 2021, 18:02

### PR DESCRIPTION
**Pull request by mcm001**
In GitLab by @matthew.morley.ca on Nov 28, 2021, 10:21

Closes #33

### CODE REVIEW

**Comment by mcm001** [comment]
In GitLab by @matthew.morley.ca on Mar 14, 2022, 16:57

added 79 commits

<ul><li>8a1e0907...4e3f0254 - 76 commits from branch <code>master</code></li><li>f62e978e - add icm-20948 driver</li><li>f614e069 - Fix things maybe</li><li>93e5cc81 - Add init</li></ul>

[Compare with previous version](/aeronu/dollar-per-foot/stm32-avionics/-/merge_requests/32/diffs?diff_id=351063934&start_sha=8a1e090788a168cd5efedd7040ead142ba24ae0a)

**Comment by mcm001** [comment]
In GitLab by @matthew.morley.ca on Apr 4, 2022, 20:23

added 1 commit

<ul><li>300be988 - fix build</li></ul>

[Compare with previous version](/aeronu/dollar-per-foot/stm32-avionics/-/merge_requests/32/diffs?diff_id=366387360&start_sha=93e5cc81ad2726a22923e537937c97d6354d954e)

**Review by notslugcat — APPROVED** [review]
test approval

**Comment by SamHaggans** [comment]
No more FCBv1 boards.

**Pull request closed without merging**
